name: Gitlab CE

on:
  push:
    branches:
      - main
    paths:
      - "gitlab-ce/**"
      - ".github/workflows/gitlab-ce.yaml"
  workflow_dispatch:

permissions:
  packages: write

env:
  IMAGE_NAME: gitlab-ce
  IMAGE_LATEST_TAG: 15.10.3

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 15.10.3
          - version: 15.9.4
          - version: 15.8.5
          - version: 15.7.8
          - version: 15.6.8
          - version: 15.5.9
          - version: 15.4.6
          - version: 15.3.5
          - version: 15.2.5
          - version: 15.1.6
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Get Semver Version
        id: get-version
        run: |
          npm install -g semver
          echo "version=$(semver --coerce ${{ matrix.version }})" >> $GITHUB_OUTPUT

      - name: Semver Parse
        uses: terradatum/semver-action@main
        id: semver
        with:
          version: ${{ steps.get-version.outputs.version }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
            verystar/${{ env.IMAGE_NAME }}
            registry.verystar.net/library/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.version }}-ce.0
            type=raw,value=${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}-ce.0
            type=raw,value=${{ steps.semver.outputs.major }}-ce.0,enable=${{ matrix.version == env.IMAGE_LATEST_TAG }}
            type=raw,value=latest,enable=${{ matrix.version == env.IMAGE_LATEST_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ACR Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.verystar.net
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{ env.IMAGE_NAME }}"
          push: true
          platforms: linux/amd64
          # linux/arm64
          build-args: |
            VERSION=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
